FROM ubuntu:19.10

RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               build-essential \
               bc \
               bison \
               binfmt-support \
               ccache \
               cdbs \
               cmake \
               cpio \
               devscripts \
               dkms \
               dpkg-dev \
               equivs \
               fakeroot \
               flex \
               gawk \
               gcc-aarch64-linux-gnu \
               cpp-aarch64-linux-gnu \
               g++-aarch64-linux-gnu \
               git \
               inotify-tools \
               kpartx \
               libgpm2 \
               lsof \
               lz4 \
               libelf-dev \
               libguestfs-tools \
               libncurses-dev \
               libssl-dev \
               libxdelta2 \
               libpython3.7 \
               linux-image-5.2.0-8-generic \
               linux-modules-5.2.0-8-generic \
               qemu-user-static \
               patch \
               rsync \
               sudo \
               vim \
               vim-common \
               vim-runtime \
               wget \
               xdelta3 \
               xxd \
               xz-utils \         
    && apt-get build-dep -y linux-image-raspi2 \
    && apt-get build-dep -y linux-image-5.2.0-8-generic \
    && apt-get upgrade -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*
