FROM ubuntu:19.10

RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               build-essential \
               bc \
               bison \
               cdbs \
               cmake \
               devscripts \
               dkms \
               equivs \
               fakeroot \
               flex \
               gawk \
               gcc-aarch64-linux-gnu \
               cpp-aarch64-linux-gnu \
               g++-aarch64-linux-gnu \
               git \
               kpartx \
               lz4 \
               libelf-dev \
               libncurses-dev \
               libssl-dev \
               patch \
               wget \
               xz-utils \         
    && apt-get build-dep -y linux-image-raspi2 \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*
